### ISSUE TITLE
Provide a simple rest endpoint for both metric/state query and dynamic configuration

### ISSUE THREAD

**Issue by wsry** [flink-extended/flink-remote-shuffle#5]
### Motivation

Currently, the metric query is supported by the metric server and no other state query or dynamic configuration is supported. A unified rest endpoint can be implemented to take care of all these requirements.

### Changes

There are many existing rest framework or web service, for example, Jersey and Jetty. We can just wrap these framework and supply some simple API like register handler and lifecycle management. Other component like ShuffleWorker and ShuffleManager can use the rest endpoint directly. In this step, metric query should be also supported and the current metric server can be removed.

### Test

- Unit test.
- Test manually on a cluster.

**Comment by TanYuxin-tyx** [comment]
Merged into master as cadb74b2437253da987f572f29066a9522a60213
