### ISSUE TITLE
flink 1.15.2 compile failed

### ISSUE THREAD

**Issue by licc** [flink-extended/flink-remote-shuffle#87]
flink 1.15.2 
`  org.apache.flink.core.classloading.ComponentClassLoader#ComponentClassLoader
`  add a  new parameter， need support. 
AkkaRpcServiceUtils   compile failed

![image](https://user-images.githubusercontent.com/4024963/192079643-1864c4ab-80a5-4d72-b38c-13eddda74d3b.png)

**Comment by wsry** [comment]
I tried 1.15.2 and it works. For Flink 1.15, master branch should be used. I am closing this issue, feel free to reopen it if there is still problem.
